#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80

# Create a symbolic link (-s optional) between the Nginx Configurations file
# an the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx
service nginx start
# Terminate the Nginx process ID
kill "$(pgrep 'nginx' | head -1)"
